package com.hexure.firelight.libraies.Enums;

public enum EnumsJSONProp {
    PRODUCT("product"),
    JURISDICTION("jurisdiction"),
    NEWPRODUCTNAME("newProductName"),
    EMAILLINK("emailLink"),
    PASSCODE("passCode"),
    OWNERPASSCODE("ownerPasscode"),
    INSUREDPASSCODE("insuredPasscode"),
    PAYORPASSCODE("payorPasscode"),
    ANNUITANTPASSCODE("annuitantPasscode"),
    OWNEREMAIL("ownerEmail"),
    INSUREDEMAIL("insuredEmail"),
    PAYOREMAIL("payorEmail"),
    ANNUITANTEMAIL("annuitantEmail"),
    RECEIPANTURL("receipantLink(url)"),
    OWNERURL("ownerUrl"),
    DOCUMENT1ANNUITANT("document1Annuitant"),
    DOCUMENT2ANNUITANT("document2Annuitant"),
    OWNERFIRSTNAME("ownerFirstName"),
    OWNERLASTNAME("ownerLastName"),
    JOINTOWNERFIRSTNAME("jointOwnerFirstName"),
    JOINTOWNERLASTNAME("jointOwnerLastName"),
    MULTILINE("multiLine"),
    RECIPIENTURL("recipientUrl"),
    RECIPIENTPASSCODE("recipientPasscode"),
    SIGNERURL("signerUrl"),
    SIGNERPASSCODE("signerPasscode"),
    AGENTURL("agentUrl"),
    AGENTPASSCODE("agentPasscode"),
    REVIEWERPASSCODE("reviewerPasscode"),
    REVIEWERURL("reviewerUrl"),
    ACTIVITYCOUNT("activityCount"),
    REVIEWERNAME("reviewerName"),
    JOINTOWNERPASSCODE("jointOwnerPasscode"),
    JOINTOWNERURL("JointOwnerUrl"),
    OWNERNAME("ownerName1"),
    INSUREDNAME("insuredName1"),
    JOINTOWNERNAME("jointOwnerName"),
    URL("URL"),
    YOURNAME("Yourname"),
    YOUREMAIL("YourEmail"),
    NEWURL("newUrl"),
    SECONDNEWPRODUCTNAME("secondNewProductName"),
    SIGNERNAME("signerName1"),
    MAILBODY("mailBody"),
    MAILDATE("mailCurrentDate"),
    REVIEWERNAMERANDOM("reviewerName1"),
    PRODUCERPASSCODE("producerPasscode"),
    AGENT3PASSCODE("agent3Passcode"),
    AGENT2PASSCODE("agent2Passcode"),
    AGENTNAME("agentName1"),
    ORDERNUMBER("orderNumber1"),

    OLDMEASSAGEVALUE("oldMessageValue"),

    NEWMESSAGEVALUE("newMessageValue"),
    NEWACTIVITYNAME("newActivityName"),
    DATAENTRYPERCENTAGE("dataEntryPercentage"),
    SEARCHCOUNT("searchCount"),
    FORMURL("formUrl"),
    REMAININGSIZE("remainingSize"),
    DATEMASKNAME("dateMaskName"),
    SSNMASKNAME("sSNMaskName"),
    ZIPMASKNAME("zipMaskName"),
    PHONEMASKNAME("phoneMaskName");

    private final String text;

    EnumsJSONProp(String text){ this.text = text;}

    public String getText(){ return  text;}
}